### ISSUE TITLE
请教U-Boot编译环境配置。

### ISSUE THREAD

**Issue by abctel** [jjm2473/rtd129x-uboot#1]
感谢作者上传代码。
最近几天一直在折腾香蕉官网u-boot的，这几天都编译失败了。
刚发现作者提供的代码也按照wiki生成了一下，同样失败了。

我的编译环境:ubuntu 16.04.7 LTS
GCC: aarch64-linux-gnu (通过APT安装)

我编译之后的错误提示：
objcopy: cannot open: image/rtd1295/v_entry.img: No such file or directory
Makefile:1164: recipe for target 'u-boot' failed
make: *** [u-boot] Error 1

编译命令：
``` shell
make CROSS_COMPILE="/home/abctel/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" rtd1296_qa_NAS_config

make CROSS_COMPILE="/home/abctel/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" menuconfig

make CROSS_COMPILE="/home/abctel/BPI-W2-bsp/toolchains/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-" V=1

```
我尝试过apt安装的gcc-aarch64-linux-gnu，也尝试过香蕉官网源码里的toolchain，都是缺少v_entry.img。

希望得到你的指点，谢谢。

**Comment by abctel** [comment]
补充一下：我的GCC版本为：
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)

**Comment by jjm2473** [comment]
我在[编译](https://github.com/jjm2473/rtd129x-uboot/wiki/%E7%BC%96%E8%AF%91)的文档里的第2步说明了，不止是下载源代码，还要下载预编译的二进制文件。`v_entry.img`就是属于二进制包里的东西，你肯定是没下载二进制包，只下载了源代码。

**Comment by jjm2473** [comment]
如果你是打算给 OpenWRT 编译 u-boot ，或者使用 OpenWRT 的工具链来编译，那就不需要看这个项目了，直接去编译 [iStoreOS](https://github.com/istoreos/istoreos) ，其中 uboot 的代码在 [uboot-realtek](https://github.com/istoreos/istoreos/tree/istoreos-21.02/package/boot/uboot-realtek)
